### Site Settings ###
title               : Abdul Hafiz Ramadan
description         : >-
                      Abdul Hafiz Ramadan is a professional android developer with more than 4 years of experience in software engineering. He has an educational background in Software Engineering and has been passionate about coding since high school and has participated in many courses and activities related to software engineering. During college he actively participated in software engineering related activities such as being a Lecturer Assistant, Mini Android Bootcamp Mentor and actively contributed to the Google Developer Student Clubs community as a head of core team for the curriculum and developer division. He has solid skills in Java, Kotlin, and JavaScript and PHP programming languages, he has a great interest in creating great user experiences and innovative products.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : abdulhafizramadan-dev/abdulhafizramadan-dev.github.io    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Abdul Hafiz Ramadan
  image             : https://github.com/abdulhafizramadan-dev/abdulhafizramadan-dev.github.io/assets/111162360/8e8904e3-24b5-45ec-b64b-85f3fcb49c76
# behance           : your_username
# dribbble          : your_username
  email             : abdulhafizramadan.dev@gmail.com
# facebook          : your_username
  github            : abdulhafizramadan-dev
# gitlab            : your_username
  instagram         : abdulhafizramadan_
# kaggle            : your_username
  linkedin          : abdul-hafiz-ramadan
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: token


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "certificate"
    values:
      layout: "certificate"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                        # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
